### ISSUE TITLE
Trojan Virus, dont make "NPM START" 

### ISSUE THREAD

**Issue by AlanWendorff** [hsinhoyeh/react-web-push-notification#1]
i start the files with NPM start and  my whole pc was infected.

**Comment by hsinhoyeh** [comment]
Hi @Kremowy 

thanks for using this package and I am sorry for using out-of-date dependencies as this repo haven't been upgraded for a while. 

I have fixed the dependency issue, please check here: https://github.com/hsinhoyeh/react-web-push-notification/commit/1756867cec468ff0d5f590e4db6b52dd8baf0a7c

please reopen this issue if you think the issue is still there. thanks
